Words:
  - Nigga
  - NIGGA
  - NiGgA
  -	nigga
  - Fuck
  - fuck
  - Fucking
  - fucking
  - Shit
  - shit
  - MotherFucker
  - Motherfucker
  - motherFucker
  - motherfucker
  - Pussy
  - pussy
  - Cock
  - cock
  - Dick
  - dick
  - Bitch
  - bitch
  - Cunt
  - cunt